steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/handy-empire-247520/rental-account', '.']
    timeout: 500s
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/handy-empire-247520/rental-account']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - set
      - image
      - deployment/rental-account #애플리케이션이름
      - rental-account-sha256=gcr.io/handy-empire-247520/rental-account
      - -n
      - default #네임스페이스
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=rental-account-cluster'
options:
  machineType: 'N1_HIGHCPU_8' # HIGHCPU로 빌드 스피드 업
timeout: 1000s # 빌드 자체에 대한 타임 아웃.